services:
  - type: web
    name: babysitting-services
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_EMAILS
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
